### ISSUE TITLE
Errors from `tsc` on declaration of `IntoEntriesIterator`

### ISSUE THREAD

**Issue by ipmcc** [Yomguithereal/obliterator#32]
When compiling, I get the following errors on the obliterator type declarations:

```
../../node_modules/obliterator/types.d.ts:18:59 - error TS1005: ',' expected.

18 export type IntoEntriesIterator<K, V> = IntoInterator<[key: K, value: V]>;
                                                             ~

../../node_modules/obliterator/types.d.ts:18:69 - error TS1005: ';' expected.

18 export type IntoEntriesIterator<K, V> = IntoInterator<[key: K, value: V]>;
                                                                       ~

../../node_modules/obliterator/types.d.ts:18:72 - error TS1005: ';' expected.

18 export type IntoEntriesIterator<K, V> = IntoInterator<[key: K, value: V]>;
                                                                          ~

../../node_modules/obliterator/types.d.ts:18:73 - error TS1109: Expression expected.

18 export type IntoEntriesIterator<K, V> = IntoInterator<[key: K, value: V]>;
                                                                           ~

../../node_modules/obliterator/types.d.ts:18:74 - error TS1109: Expression expected.

18 export type IntoEntriesIterator<K, V> = IntoInterator<[key: K, value: V]>;
                                                                            ~


Found 5 errors.
```
I'm using:
* typescript: 3.9.10
* node: 16.15.0 (LTS of 16)
* obliterator: 2.0.3

I can find no reference for this `[key: X value: Y]` syntax (as used: `IntoInterator<[key: K, value: V]>`) anywhere in the typescript docs. Based on [this page](https://www.typescriptlang.org/docs/handbook/2/keyof-types.html), it looks like it should be `{ [key: K]: V }` (and, indeed, changing it to that makes the compiler happy, despite being a solution that'll get overwritten the next time I `yarn install`)

Then again, I might be doing something wrong... I just can't find any indication that this is a valid type declaration in any version of TypeScript.

**Comment by Yomguithereal** [comment]
Hello @ipmcc. This syntax is called a "labeled tuple" in TS and can be found on this documentation page (albeit not straigthforward to find): https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html

I think they were introduced in TS v4, hence the problem you are having. Is this ok for you to upgrade from TS v3 to v4?

**Comment by ipmcc** [comment]
Thanks for the pointer! TIL. For my project, I have a big chain of dependencies (which I don't control) that effectively means I cannot upgrade to TS4+ for some time. I'm working on a React Native app that uses [Expo](https://expo.dev) -- a broad support ecosystem and toolset for developing multi-platform mobile apps using React Native. 

Expo's cloud build system requires that you use Node.js 16 and then the requirements ripple out from there. The `@node/types` package that corresponds with Node.js v16.15.0 (the current, mainline LTS version) is v16.11.7, and that is, in turn, tied to TS3.7 (per `npm dist-tag ls @types/node`). I've tried using a newer version of TS (v4.5.5) with the rest of this ecosystem, and the result is literally thousands of errors, whereas when I downgrade to TS3.7 I get no errors (other than this one). 

I deeply sympathize with the urge to use the latest and greatest, but I'm pretty well hamstrung unless I want to move off of Expo (which would entail a huge amount of work to replicate all the things they give app developers "for free"). 

I guess my question would be, "What would you, as the owner of obliterator, 'lose' by using the older, more compatible type annotation syntax?" If you just don't want to, that's fine, and that's your prerogative for sure, but (and I'm not an expert here, so I could be completely talking out my butt here) it doesn't look like you'd lose anything by using the older syntax, and you'd gain the ability for users of the current, mainline Long Term Support version of Node.js to use your package without hacking it, forking it, ignoring errors, or simply moving on.

**Comment by Yomguithereal** [comment]
@ipmcc I don't have any issue "downgrading" to non-labeled tuples in `obliterator`, but what I worry about is the following: are you using `obliterator` directly? Or are you requiring because of some of your dependencies use it. I ask because I know for a fact that a lot of libs relying on `obliterator` also use labeled tuples in their types, which means downgrading types here will only move the problem to the next dependency.

**Comment by ipmcc** [comment]
Personally, I'm using it directly, so I don't anticipate that being a problem.

**Comment by Yomguithereal** [comment]
@ipmcc v2.0.4 should be live on npm without the labeled tuple. Can you report here to tell me if this fixes your problem?

**Comment by ipmcc** [comment]
Yup! That solved the issue. Thanks for being so responsive. I really appreciate it. And thanks for writing such a useful package.
